/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BloodGUI.java
 *
  */
package com.mycompany.bloodtestapp;

import static java.lang.Integer.parseInt;

public class BloodGUI extends javax.swing.JFrame {

    /** Creates new form BloodGUI */
    private PQInterface myPQueue;
    
    public BloodGUI() {
        myPQueue = new MyPriorityQueue();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wardRbtn = new javax.swing.ButtonGroup();
        appTitleLbl = new javax.swing.JLabel();
        nameJLabel = new javax.swing.JLabel();
        priorityLbl = new javax.swing.JLabel();
        nameTf = new javax.swing.JTextField();
        gpTf = new javax.swing.JTextField();
        numPatientsBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        displayJLabel = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTa = new javax.swing.JTextArea();
        gpLbl = new javax.swing.JLabel();
        priorityTf = new javax.swing.JTextField();
        listBtn = new javax.swing.JButton();
        noShowBtn = new javax.swing.JButton();
        ageLbl = new javax.swing.JLabel();
        ageTf = new javax.swing.JTextField();
        gpLbl1 = new javax.swing.JLabel();
        noRb = new javax.swing.JRadioButton();
        yesRb = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        appTitleLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        appTitleLbl.setForeground(new java.awt.Color(255, 0, 0));
        appTitleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appTitleLbl.setText("Blood Test Scheduler");

        nameJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nameJLabel.setForeground(new java.awt.Color(0, 51, 204));
        nameJLabel.setText("Patient's name:");

        priorityLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        priorityLbl.setForeground(new java.awt.Color(0, 51, 204));
        priorityLbl.setText("Set priority(Urgent/Medium/Low):");

        nameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTfActionPerformed(evt);
            }
        });

        numPatientsBtn.setText("No. of patients");
        numPatientsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPatientsBtnActionPerformed(evt);
            }
        });

        addBtn.setText("Add patient to waiting list");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        removeBtn.setText("Next patient");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        displayJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        displayTa.setColumns(20);
        displayTa.setRows(5);
        jScrollPane1.setViewportView(displayTa);

        gpLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        gpLbl.setForeground(new java.awt.Color(0, 51, 204));
        gpLbl.setText("GP Details:");

        priorityTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priorityTfActionPerformed(evt);
            }
        });

        listBtn.setText("Waiting patients");
        listBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listBtnActionPerformed(evt);
            }
        });

        noShowBtn.setText("Print No Shows");
        noShowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noShowBtnActionPerformed(evt);
            }
        });

        ageLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ageLbl.setForeground(new java.awt.Color(0, 51, 204));
        ageLbl.setText("Patient's Age:");

        ageTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTfActionPerformed(evt);
            }
        });

        gpLbl1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        gpLbl1.setForeground(new java.awt.Color(0, 51, 204));
        gpLbl1.setText("Are they from the Hospital ward?");

        wardRbtn.add(noRb);
        noRb.setText("No");
        noRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noRbActionPerformed(evt);
            }
        });

        wardRbtn.add(yesRb);
        yesRb.setText("Yes");
        yesRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesRbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(displayJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameJLabel)
                            .addComponent(ageLbl)
                            .addComponent(gpLbl)
                            .addComponent(gpLbl1)
                            .addComponent(priorityLbl))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ageTf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(gpTf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(yesRb)
                                .addGap(18, 18, 18)
                                .addComponent(noRb))
                            .addComponent(priorityTf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTf))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(appTitleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(listBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addComponent(numPatientsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(noShowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(appTitleLbl)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gpLbl1)
                    .addComponent(noRb)
                    .addComponent(yesRb))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gpLbl)
                    .addComponent(gpTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priorityLbl)
                    .addComponent(priorityTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numPatientsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noShowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(displayJLabel))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTfActionPerformed

    private void numPatientsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPatientsBtnActionPerformed
        // TODO add your handling code here:
        displayTa.append("There are " + myPQueue.size() + " patients on the waiting list\n");
    }//GEN-LAST:event_numPatientsBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        String name, gp;
        String priority;
        int age;
        boolean fromWard;
        
        Patient newPatient = new Patient();
        name = nameTf.getText();
        gp = gpTf.getText();
        age = Integer.parseInt(ageTf.getText());
        fromWard = yesRb.isSelected();
        
        newPatient.setName(name);
        newPatient.setGp(gp);
        newPatient.setAge(age);
        newPatient.setFromHospitalWard(fromWard);
        
        priority = priorityTf.getText();
        myPQueue.enqueue(priority, newPatient);

        displayTa.append(nameTf.getText() + " has been successfully added to the waiting list\n");
        nameTf.setText("");
        gpTf.setText("");
        priorityTf.setText("");
    }//GEN-LAST:event_addBtnActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        // TODO add your handling code here:

        if(!myPQueue.isEmpty()){
            PQElement pqElement = (PQElement)myPQueue.dequeue();
            Patient patient = (Patient)pqElement.getPatient();
            
            displayTa.append("The doctor will now see " + patient.getName() +"\n");
            displayTa.append("Age: " + patient.getAge()+ "\n");
            displayTa.append("From Hospital Ward?: " + patient.isFromHospitalWard()+ "\n");
            displayTa.append("GP Details: " + patient.getGp()+ "\n");
            displayTa.append("Their priority is: " + pqElement.getPriority()+ "\n");
            
        }
        else
            displayTa.append("There are no patients waiting!\n");
    }//GEN-LAST:event_removeBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void priorityTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priorityTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priorityTfActionPerformed

    private void listBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listBtnActionPerformed
        // TODO add your handling code here:
        displayTa.append("The patients on the waiting list are...\n");
        displayTa.append(myPQueue.printPQueue()+ "\n");
    }//GEN-LAST:event_listBtnActionPerformed

    private void noShowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noShowBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noShowBtnActionPerformed

    private void ageTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTfActionPerformed

    private void noRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noRbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noRbActionPerformed

    private void yesRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesRbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yesRbActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel ageLbl;
    private javax.swing.JTextField ageTf;
    private javax.swing.JLabel appTitleLbl;
    private javax.swing.JLabel displayJLabel;
    private javax.swing.JTextArea displayTa;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel gpLbl;
    private javax.swing.JLabel gpLbl1;
    private javax.swing.JTextField gpTf;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listBtn;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JTextField nameTf;
    private javax.swing.JRadioButton noRb;
    private javax.swing.JButton noShowBtn;
    private javax.swing.JButton numPatientsBtn;
    private javax.swing.JLabel priorityLbl;
    private javax.swing.JTextField priorityTf;
    private javax.swing.JButton removeBtn;
    private javax.swing.ButtonGroup wardRbtn;
    private javax.swing.JRadioButton yesRb;
    // End of variables declaration//GEN-END:variables

}
